// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA2mWutgBqUZ0nZGMXXl85NMOhtpnu-Vo',
    appId: '1:44836736616:web:e5c43dc6e9b072eb0f75dd',
    messagingSenderId: '44836736616',
    projectId: 'nexaera',
    authDomain: 'nexaera.firebaseapp.com',
    storageBucket: 'nexaera.appspot.com',
    measurementId: 'G-JSJWYM5ZGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByy7tXenBHF-f3Wgqcxcof0BVBw-MfPD8',
    appId: '1:44836736616:android:b9a7e8050be0b99b0f75dd',
    messagingSenderId: '44836736616',
    projectId: 'nexaera',
    storageBucket: 'nexaera.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGtgW-MXLGXRLuPPJX4-lQcrpDa1sPPqg',
    appId: '1:44836736616:ios:35f07b1d69e2e8ea0f75dd',
    messagingSenderId: '44836736616',
    projectId: 'nexaera',
    storageBucket: 'nexaera.appspot.com',
    iosClientId: '44836736616-9botmptirpfcqqs72cmd89aq3gjnifg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexaeraChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGtgW-MXLGXRLuPPJX4-lQcrpDa1sPPqg',
    appId: '1:44836736616:ios:35f07b1d69e2e8ea0f75dd',
    messagingSenderId: '44836736616',
    projectId: 'nexaera',
    storageBucket: 'nexaera.appspot.com',
    iosClientId: '44836736616-9botmptirpfcqqs72cmd89aq3gjnifg4.apps.googleusercontent.com',
    iosBundleId: 'com.example.nexaeraChat',
  );
}
